name: fi_mapxus_positioning_flutter
description: "A Flutter plugin for Mapxus indoor positioning services. Provides real-time location tracking and positioning state management for indoor navigation applications."
version: 1.0.1
homepage: https://github.com/fidenzappdev/fi_mapxus_positioning_flutter
repository: https://github.com/fidenzappdev/fi_mapxus_positioning_flutter
issue_tracker: https://github.com/fidenzappdev/fi_mapxus_positioning_flutter/issues

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.fidenz.mapxus_positioning_flutter
        pluginClass: MapxusPositioningFlutterPlugin
